### ISSUE TITLE
Chalo app detecting root (it's a bus tracking app)

### ISSUE THREAD

**Issue by parasgargexx20** [tiann/KernelSU#1142]
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

Chalo app detecting root

Safetynet passes 
Device integrity passes
ZygiskNext module is present

### To Reproduce

1. Go to playstore install chalo app (for live bus tracking)

2. Open the app

3. See the error which says device is rooted

### Expected behavior

It shouldn't be detectable (otherwise defeats the purpose of having kernelsu)

### Screenshots

![Screenshot_20231114-110603_Pixel Launcher](https://github.com/tiann/KernelSU/assets/102552831/19eea2aa-1e94-4c83-908c-d39633d76b9f)
![Screenshot_20231114-110607_Pixel Launcher](https://github.com/tiann/KernelSU/assets/102552831/363fefd1-2632-481a-83c9-ded9c03e6145)
![Screenshot_20231114-110720_KernelSU](https://github.com/tiann/KernelSU/assets/102552831/84a31046-5447-44d6-a6ac-28466e1ff772)
![Screenshot_20231114-110724_KernelSU](https://github.com/tiann/KernelSU/assets/102552831/190acb30-3bcc-4ddb-af4f-0da708539ddc)
![Screenshot_20231114-110905_Yet Another SafetyNet Attestation Checker](https://github.com/tiann/KernelSU/assets/102552831/0c924336-3277-4bde-befa-e39dcba6d49a)
![Screenshot_20231114-110953_Play Integrity API Checker](https://github.com/tiann/KernelSU/assets/102552831/4f17e289-f5e7-4885-ba34-98a61a5f21d8)
![Screenshot_20231114-111027_Settings](https://github.com/tiann/KernelSU/assets/102552831/ccddca8e-3f3f-4077-8902-d6eff0694274)
![Screenshot_20231114-111404_KernelSU](https://github.com/tiann/KernelSU/assets/102552831/d1e5a7db-03bf-4222-8a04-d02d2c97a8f2)

### Logs

[KernelSU_bugreport_2023-11-14_11_11.tar.gz.zip](https://github.com/tiann/KernelSU/files/13344966/KernelSU_bugreport_2023-11-14_11_11.tar.gz.zip)

### Device info

- Device: Redmi Note 9 Pro 4G (miatoll)
- OS Version: 14
- KernelSU Version: 0.7.0
- Kernel Version: 4.14.329

### Additional context

I'm running a14 (second build of evo x) (nov patch)

**Comment by rushiranpise** [comment]
1. Try uninstalling kernel su manager app
2. Try disabling zygisk
3. Try disabling all modules

**Comment by parasgargexx20** [comment]
> 1. Try uninstalling kernel su manager app
> 2. Try disabling zygisk
> 3. Try disabling all modules

I now tried booting to safe mode (disables all module)

Then turn off device and boot it (now I didn't enable the overlay fs which convert read only system to read and write)

And chalo app opened 

(Turns out it was detecting read and write permission somehow)

**Comment by BlackMesa123** [comment]
Did you try disabling all the modules to see if this is caused by any of them?

**Comment by parasgargexx20** [comment]
> Did you try disabling all the modules to see if this is caused by any of them?

It was caused by magisk overlay fs module which is used to convert system from read only to read and write
